import { defineObject, FieldType } from 'twenty-sdk/define';

export const DOCUMENT_UNIVERSAL_IDENTIFIER = "2bac2815-4060-4f0b-a35d-1eb5bc22ed38";
export const DOCUMENT_DOCUMENT_CATEGORY_FIELD_ID = "3af14528-b7d5-44f5-8006-a691d659854b";
export const DOCUMENT_DOCUMENT_STATUS_FIELD_ID = "38d70ba3-1177-440a-91f2-1e2422e11202";
export const DOCUMENT_DOCUMENT_DATE_FIELD_ID = "db87d06a-f5fb-4893-b10d-b5137a98fd39";
export const DOCUMENT_FILE_FIELD_ID = "84798a7c-5370-443f-86d2-4a1f9527f4ea";
export const DOCUMENT_REFERENCE_NUMBER_FIELD_ID = "d168c668-5cf9-4667-94d4-30c5b861b089";
export const DOCUMENT_NOTES_FIELD_ID = "c1a9efec-7d33-4910-9567-c21f0e77ed18";
export const DOCUMENT_REQUIRED_FOR_COMPLIANCE_FIELD_ID = "0d464dd0-57ea-4ae9-bc28-99a884c13eaa";
export const DOCUMENT_NAME_FIELD_ID = "c4d0f4cf-ad04-55a3-b033-36881d45ee68";
export const DOCUMENT_DOCUMENT_TYPE_FIELD_ID = "ce05746d-418a-44a2-aa35-9b242b07796c";
export const DOCUMENT_ISSUING_AUTHORITY_FIELD_ID = "4f631d33-4cc9-40a2-9235-4014544375d9";
export const DOCUMENT_EXPIRY_DATE_FIELD_ID = "9247ad08-b089-4023-b81a-d025836a5354";

export default defineObject({
  universalIdentifier: DOCUMENT_UNIVERSAL_IDENTIFIER,
  nameSingular: "document",
  namePlural: "documents",
  labelSingular: "Document",
  labelPlural: "Documents",
  description: "Title chain, approvals and statutory filings. In India title is established by an unbroken chain of documents, so this is load-bearing, not administrative.",
  icon: "IconFileText",
  labelIdentifierFieldMetadataUniversalIdentifier: DOCUMENT_NAME_FIELD_ID,
  fields: [
    {
      universalIdentifier: DOCUMENT_DOCUMENT_CATEGORY_FIELD_ID,
      type: FieldType.SELECT,
      name: "documentCategory",
      label: "Category",
      icon: "IconFolders",
      isNullable: true,
      options: [
      { value: "TITLE_CHAIN", label: "Title Chain", position: 0, color: "green" },
      { value: "APPROVALS", label: "Approvals", position: 1, color: "purple" },
      { value: "TRANSACTION", label: "Transaction", position: 2, color: "blue" },
      { value: "FINANCIAL", label: "Financial", position: 3, color: "sky" },
      { value: "STATUTORY", label: "Statutory", position: 4, color: "red" },
      { value: "PARTY_KYC", label: "Party KYC", position: 5, color: "gray" },
      { value: "RENTAL", label: "Rental", position: 6, color: "turquoise" },
      ],
    },
    {
      universalIdentifier: DOCUMENT_DOCUMENT_STATUS_FIELD_ID,
      type: FieldType.SELECT,
      name: "documentStatus",
      label: "Status",
      icon: "IconProgressCheck",
      isNullable: true,
      options: [
      { value: "NOT_STARTED", label: "Not Started", position: 0, color: "gray" },
      { value: "REQUESTED", label: "Requested", position: 1, color: "yellow" },
      { value: "RECEIVED", label: "Received", position: 2, color: "blue" },
      { value: "UNDER_REVIEW", label: "Under Review", position: 3, color: "orange" },
      { value: "VERIFIED", label: "Verified", position: 4, color: "green" },
      { value: "REJECTED", label: "Rejected", position: 5, color: "red" },
      { value: "EXPIRED", label: "Expired", position: 6, color: "gray" },
      ],
    },
    {
      universalIdentifier: DOCUMENT_DOCUMENT_DATE_FIELD_ID,
      type: FieldType.DATE,
      name: "documentDate",
      label: "Document Date",
      icon: "IconCalendar",
      isNullable: true,
    },
    {
      universalIdentifier: DOCUMENT_FILE_FIELD_ID,
      type: FieldType.FILES,
      name: "file",
      label: "File",
      icon: "IconPaperclip",
      isNullable: true,
      universalSettings: {"maxNumberOfValues": 20},
    },
    {
      universalIdentifier: DOCUMENT_REFERENCE_NUMBER_FIELD_ID,
      type: FieldType.TEXT,
      name: "referenceNumber",
      label: "Reference Number",
      icon: "IconHash",
      isNullable: true,
    },
    {
      universalIdentifier: DOCUMENT_NOTES_FIELD_ID,
      type: FieldType.TEXT,
      name: "notes",
      label: "Notes",
      icon: "IconNotes",
      isNullable: true,
    },
    {
      universalIdentifier: DOCUMENT_REQUIRED_FOR_COMPLIANCE_FIELD_ID,
      type: FieldType.BOOLEAN,
      name: "requiredForCompliance",
      label: "Required for Compliance",
      description: "Drives the pre-registration missing-documents checklist.",
      icon: "IconShieldCheck",
      isNullable: true,
    },
    {
      universalIdentifier: DOCUMENT_NAME_FIELD_ID,
      type: FieldType.TEXT,
      name: "name",
      label: "Name",
      description: "Name",
      icon: "IconAbc",
      isNullable: true,
    },
    {
      universalIdentifier: DOCUMENT_DOCUMENT_TYPE_FIELD_ID,
      type: FieldType.SELECT,
      name: "documentType",
      label: "Document Type",
      icon: "IconFileText",
      isNullable: true,
      options: [
      { value: "SALE_DEED", label: "Sale Deed", position: 0, color: "green" },
      { value: "MOTHER_DEED", label: "Mother Deed / Parent Documents", position: 1, color: "green" },
      { value: "ENCUMBRANCE_CERT", label: "Encumbrance Certificate", position: 2, color: "green" },
      { value: "KHATA_CERT", label: "Khata Certificate", position: 3, color: "green" },
      { value: "KHATA_EXTRACT", label: "Khata Extract", position: 4, color: "green" },
      { value: "MUTATION_EXTRACT", label: "Mutation Register Extract", position: 5, color: "green" },
      { value: "TAX_RECEIPTS", label: "Property Tax Receipts", position: 6, color: "green" },
      { value: "SURVEY_SKETCH", label: "Survey Sketch", position: 7, color: "green" },
      { value: "PARTITION_DEED", label: "Partition Deed", position: 8, color: "green" },
      { value: "GIFT_DEED", label: "Gift Deed", position: 9, color: "green" },
      { value: "WILL_SUCCESSION", label: "Will / Succession Certificate", position: 10, color: "green" },
      { value: "POWER_OF_ATTORNEY", label: "Power of Attorney", position: 11, color: "red" },
      { value: "RTC_PAHANI", label: "RTC / Pahani / 7-12 Extract", position: 12, color: "green" },
      { value: "RERA_CERT", label: "RERA Registration Certificate", position: 13, color: "purple" },
      { value: "BUILDING_PLAN", label: "Approved Building Plan", position: 14, color: "purple" },
      { value: "COMMENCEMENT_CERT", label: "Commencement Certificate", position: 15, color: "purple" },
      { value: "OCCUPANCY_CERT", label: "Occupancy Certificate", position: 16, color: "purple" },
      { value: "COMPLETION_CERT", label: "Completion Certificate", position: 17, color: "purple" },
      { value: "FIRE_NOC", label: "Fire NOC", position: 18, color: "purple" },
      { value: "ENVIRONMENT_CLEARANCE", label: "Environment Clearance", position: 19, color: "purple" },
      { value: "LAND_CONVERSION", label: "Land Conversion Certificate", position: 20, color: "purple" },
      { value: "AGREEMENT_TO_SELL", label: "Agreement to Sell", position: 21, color: "blue" },
      { value: "ALLOTMENT_LETTER", label: "Allotment Letter", position: 22, color: "blue" },
      { value: "BBA", label: "Builder-Buyer Agreement", position: 23, color: "blue" },
      { value: "SALE_DEED_DRAFT", label: "Sale Deed Draft", position: 24, color: "blue" },
      { value: "POSSESSION_LETTER", label: "Possession Letter", position: 25, color: "blue" },
      { value: "HANDOVER_CHECKLIST", label: "Handover Checklist", position: 26, color: "blue" },
      { value: "NOC_SOCIETY", label: "NOC - Society", position: 27, color: "yellow" },
      { value: "NOC_BANK", label: "NOC - Bank", position: 28, color: "yellow" },
      { value: "NOC_BUILDER", label: "NOC - Builder", position: 29, color: "yellow" },
      { value: "LOAN_SANCTION", label: "Loan Sanction Letter", position: 30, color: "sky" },
      { value: "DISBURSEMENT_LETTER", label: "Disbursement Letter", position: 31, color: "sky" },
      { value: "STAMP_DUTY_CHALLAN", label: "Stamp Duty Challan", position: 32, color: "orange" },
      { value: "REGISTRATION_RECEIPT", label: "Registration Receipt", position: 33, color: "orange" },
      { value: "FORM_26QB", label: "Form 26QB (TDS)", position: 34, color: "red" },
      { value: "GST_INVOICE", label: "GST Invoice", position: 35, color: "orange" },
      { value: "PAYMENT_PROOF", label: "Bank Statement / Payment Proof", position: 36, color: "sky" },
      { value: "PAN_CARD", label: "PAN Card", position: 37, color: "gray" },
      { value: "ADDRESS_PROOF", label: "Address Proof", position: 38, color: "gray" },
      { value: "PHOTOGRAPHS", label: "Photographs", position: 39, color: "gray" },
      { value: "LEAVE_LICENSE", label: "Leave and License Agreement", position: 40, color: "turquoise" },
      { value: "POLICE_VERIFICATION", label: "Police Verification Form", position: 41, color: "turquoise" },
      { value: "INVENTORY_LIST", label: "Inventory List", position: 42, color: "turquoise" },
      { value: "DEPOSIT_RECEIPT", label: "Deposit Receipt", position: 43, color: "turquoise" },
      { value: "LEGAL_OPINION", label: "Legal Opinion / Title Report", position: 44, color: "pink" },
      { value: "OTHER", label: "Other", position: 45, color: "gray" },
      ],
    },
    {
      universalIdentifier: DOCUMENT_ISSUING_AUTHORITY_FIELD_ID,
      type: FieldType.TEXT,
      name: "issuingAuthority",
      label: "Issuing Authority",
      icon: "IconBuildingBank",
      isNullable: true,
    },
    {
      universalIdentifier: DOCUMENT_EXPIRY_DATE_FIELD_ID,
      type: FieldType.DATE,
      name: "expiryDate",
      label: "Expiry Date",
      icon: "IconCalendarX",
      isNullable: true,
    },
  ],
});
