import { defineObject, FieldType } from 'twenty-sdk/define';

export const MILESTONE_UNIVERSAL_IDENTIFIER = "02d7ba27-d412-4fd4-9997-380dd6b01939";
export const MILESTONE_MILESTONE_STATUS_FIELD_ID = "2308152c-48c2-484d-aff3-364d57eb57bb";
export const MILESTONE_MILESTONE_TYPE_FIELD_ID = "974f41e1-aa6e-4be5-adb1-80831e2e80ac";
export const MILESTONE_IS_CRITICAL_FIELD_ID = "dd61b96f-dcb6-4222-b44d-954f9e13d827";
export const MILESTONE_DUE_DATE_FIELD_ID = "3be032ed-28ee-4165-ab93-34a604832e8f";
export const MILESTONE_RESPONSIBLE_PARTY_FIELD_ID = "a7dc290b-7af9-4324-9a0e-62c9e98b60b8";
export const MILESTONE_NAME_FIELD_ID = "f71e1526-0da7-5531-b33c-fe2cf091a9ef";
export const MILESTONE_COMPLETED_DATE_FIELD_ID = "c184ce12-a0f5-4e48-9bde-091d0156a420";
export const MILESTONE_BLOCKER_NOTES_FIELD_ID = "4f26a2e4-73e3-4b22-9561-87bee8bc5ead";

export default defineObject({
  universalIdentifier: MILESTONE_UNIVERSAL_IDENTIFIER,
  nameSingular: "milestone",
  namePlural: "milestones",
  labelSingular: "Milestone",
  labelPlural: "Milestones",
  description: "Dated legal, financial and handover step within a transaction.",
  icon: "IconChecklist",
  labelIdentifierFieldMetadataUniversalIdentifier: MILESTONE_NAME_FIELD_ID,
  fields: [
    {
      universalIdentifier: MILESTONE_MILESTONE_STATUS_FIELD_ID,
      type: FieldType.SELECT,
      name: "milestoneStatus",
      label: "Status",
      icon: "IconProgressCheck",
      isNullable: true,
      options: [
      { value: "PENDING", label: "Pending", position: 0, color: "gray" },
      { value: "IN_PROGRESS", label: "In Progress", position: 1, color: "blue" },
      { value: "COMPLETED", label: "Completed", position: 2, color: "green" },
      { value: "DELAYED", label: "Delayed", position: 3, color: "orange" },
      { value: "WAIVED", label: "Waived", position: 4, color: "purple" },
      { value: "BLOCKED", label: "Blocked", position: 5, color: "red" },
      ],
    },
    {
      universalIdentifier: MILESTONE_MILESTONE_TYPE_FIELD_ID,
      type: FieldType.SELECT,
      name: "milestoneType",
      label: "Milestone",
      icon: "IconChecklist",
      isNullable: true,
      options: [
      { value: "TOKEN_RECEIPT", label: "Token Receipt", position: 0, color: "green" },
      { value: "ATS_DRAFTED", label: "Agreement to Sell Drafted", position: 1, color: "blue" },
      { value: "ATS_EXECUTED", label: "ATS Executed", position: 2, color: "blue" },
      { value: "ATS_REGISTERED", label: "ATS Registered", position: 3, color: "blue" },
      { value: "LOAN_APPLICATION", label: "Loan Application Submitted", position: 4, color: "sky" },
      { value: "LOAN_SANCTION", label: "Loan Sanction Letter", position: 5, color: "sky" },
      { value: "TITLE_SEARCH", label: "Title Search Started", position: 6, color: "purple" },
      { value: "LEGAL_OPINION", label: "Legal Opinion Received", position: 7, color: "purple" },
      { value: "EC_OBTAINED", label: "Encumbrance Certificate", position: 8, color: "purple" },
      { value: "SOCIETY_NOC", label: "Society NOC", position: 9, color: "yellow" },
      { value: "BANK_NOC", label: "Bank NOC", position: 10, color: "yellow" },
      { value: "BUILDER_NOC", label: "Builder NOC", position: 11, color: "yellow" },
      { value: "SALE_DEED_DRAFTED", label: "Sale Deed Drafted", position: 12, color: "orange" },
      { value: "STAMP_DUTY_PAID", label: "Stamp Duty Paid", position: 13, color: "orange" },
      { value: "TDS_PAID", label: "TDS Paid (Form 26QB)", position: 14, color: "red" },
      { value: "REGISTRATION_BOOKED", label: "Registration Appointment Booked", position: 15, color: "turquoise" },
      { value: "SALE_DEED_REGISTERED", label: "Sale Deed Registered", position: 16, color: "green" },
      { value: "LOAN_DISBURSED", label: "Loan Disbursed", position: 17, color: "sky" },
      { value: "POSSESSION_HANDOVER", label: "Possession Handover", position: 18, color: "green" },
      { value: "MUTATION", label: "Mutation / Khata Transfer", position: 19, color: "turquoise" },
      { value: "ELECTRICITY_TRANSFER", label: "Electricity Meter Transfer", position: 20, color: "gray" },
      { value: "WATER_TRANSFER", label: "Water Connection Transfer", position: 21, color: "gray" },
      { value: "SOCIETY_MEMBERSHIP", label: "Society Membership Transfer", position: 22, color: "gray" },
      { value: "ALLOTMENT_LETTER", label: "Allotment Letter", position: 23, color: "blue" },
      { value: "BBA", label: "Builder-Buyer Agreement", position: 24, color: "blue" },
      { value: "CONSTRUCTION_PAYMENT", label: "Construction Milestone Payment", position: 25, color: "orange" },
      { value: "OC_RECEIVED", label: "Occupancy Certificate", position: 26, color: "green" },
      { value: "CC_RECEIVED", label: "Completion Certificate", position: 27, color: "green" },
      { value: "SNAG_LIST", label: "Snag List", position: 28, color: "yellow" },
      { value: "FINAL_HANDOVER", label: "Final Handover", position: 29, color: "green" },
      { value: "RENT_AGREEMENT_DRAFTED", label: "Rent Agreement Drafted", position: 30, color: "blue" },
      { value: "POLICE_VERIFICATION", label: "Police Verification", position: 31, color: "yellow" },
      { value: "AGREEMENT_REGISTERED", label: "Agreement Registered", position: 32, color: "blue" },
      { value: "DEPOSIT_RECEIVED", label: "Security Deposit Received", position: 33, color: "green" },
      { value: "INVENTORY_CHECK", label: "Handover / Inventory Check", position: 34, color: "gray" },
      { value: "UTILITY_TRANSFER", label: "Utility Transfer", position: 35, color: "gray" },
      { value: "RENT_DUE", label: "Rent Due", position: 36, color: "orange" },
      { value: "OTHER", label: "Other", position: 37, color: "gray" },
      ],
    },
    {
      universalIdentifier: MILESTONE_IS_CRITICAL_FIELD_ID,
      type: FieldType.BOOLEAN,
      name: "isCritical",
      label: "Critical",
      description: "Missing this one kills the deal.",
      icon: "IconAlertTriangle",
      isNullable: true,
    },
    {
      universalIdentifier: MILESTONE_DUE_DATE_FIELD_ID,
      type: FieldType.DATE,
      name: "dueDate",
      label: "Due Date",
      icon: "IconCalendarDue",
      isNullable: true,
    },
    {
      universalIdentifier: MILESTONE_RESPONSIBLE_PARTY_FIELD_ID,
      type: FieldType.SELECT,
      name: "responsibleParty",
      label: "Responsible",
      icon: "IconUser",
      isNullable: true,
      options: [
      { value: "BUYER", label: "Buyer", position: 0, color: "green" },
      { value: "SELLER", label: "Seller", position: 1, color: "turquoise" },
      { value: "OUR_AGENT", label: "Our Agent", position: 2, color: "sky" },
      { value: "COUNTERPARTY_AGENT", label: "Counterparty Agent", position: 3, color: "blue" },
      { value: "BANK", label: "Bank", position: 4, color: "purple" },
      { value: "ADVOCATE", label: "Advocate", position: 5, color: "pink" },
      { value: "BUILDER", label: "Builder", position: 6, color: "red" },
      { value: "SOCIETY", label: "Society", position: 7, color: "orange" },
      { value: "GOVERNMENT", label: "Government Office", position: 8, color: "yellow" },
      ],
    },
    {
      universalIdentifier: MILESTONE_NAME_FIELD_ID,
      type: FieldType.TEXT,
      name: "name",
      label: "Name",
      description: "Name",
      icon: "IconAbc",
      isNullable: true,
    },
    {
      universalIdentifier: MILESTONE_COMPLETED_DATE_FIELD_ID,
      type: FieldType.DATE,
      name: "completedDate",
      label: "Completed On",
      icon: "IconCalendarCheck",
      isNullable: true,
    },
    {
      universalIdentifier: MILESTONE_BLOCKER_NOTES_FIELD_ID,
      type: FieldType.TEXT,
      name: "blockerNotes",
      label: "Blocker Notes",
      icon: "IconAlertCircle",
      isNullable: true,
    },
  ],
});
