import { defineObject, FieldType, NumberDataType } from 'twenty-sdk/define';

export const PROPERTY_UNIVERSAL_IDENTIFIER = "96396b13-d599-4418-b1e1-e7dc1b09882a";
export const PROPERTY_PHOTOS_FIELD_ID = "f53d4020-c63e-4c73-9f35-1aba8bdaae7b";
export const PROPERTY_BEDROOMS_FIELD_ID = "517ca4c7-fadc-4951-b0a4-e6d471ad08f7";
export const PROPERTY_OPEN_PARKING_FIELD_ID = "9009a737-5628-453d-897b-01b6af792425";
export const PROPERTY_WATER_SOURCE_FIELD_ID = "d9de6237-46f8-4bc3-8336-dbc4a3aa33cb";
export const PROPERTY_AGE_OF_PROPERTY_FIELD_ID = "9370c9ab-c286-49c8-abe2-b95e8dde6f04";
export const PROPERTY_COVERED_PARKING_FIELD_ID = "9743d48e-ec16-4b3a-8fae-e6294894ddee";
export const PROPERTY_VASTU_COMPLIANT_FIELD_ID = "627ce69d-9f7f-4497-b500-d372e8d8ad45";
export const PROPERTY_BUILT_UP_AREA_FIELD_ID = "5de4429f-73c5-41d9-bd43-e28ecd8bf5ab";
export const PROPERTY_EXISTING_RENT_FIELD_ID = "fb660c2c-5daf-4462-8199-a27bc3616881";
export const PROPERTY_SOCIETY_NAME_FIELD_ID = "ec4e09e3-1671-437a-b0e9-9f4bf0977583";
export const PROPERTY_KHATA_TYPE_FIELD_ID = "455e2e16-3db0-4dcb-bf41-cecea463057f";
export const PROPERTY_PROPERTY_TYPE_FIELD_ID = "ad2f5497-c07b-4426-abe4-1f44b40e8a6c";
export const PROPERTY_POLLUTION_BOARD_CATEGORY_FIELD_ID = "24f35fed-63a3-4c65-b98f-58c2323a8365";
export const PROPERTY_RTC_PAHANI_NUMBER_FIELD_ID = "7713748c-9cbc-4463-85d5-a17e4ef908e2";
export const PROPERTY_FENCING_FIELD_ID = "488c05fd-f3e4-4d34-a5fe-03416240d059";
export const PROPERTY_RENTAL_YIELD_PCT_FIELD_ID = "61f52e37-09ba-4f61-afb9-e4f8ae05b495";
export const PROPERTY_LAYOUT_APPROVAL_FIELD_ID = "3797e4f6-fd89-4a24-8b5e-b947b46d20cf";
export const PROPERTY_GATED_COMMUNITY_FIELD_ID = "965c1a0c-bed7-4f96-80e7-85cc885a1e06";
export const PROPERTY_EAVE_HEIGHT_FEET_FIELD_ID = "86a78bba-d667-4d64-9ce3-75350311bf68";
export const PROPERTY_CIRCLE_RATE_VALUE_FIELD_ID = "5c08e881-54c0-49bb-ae54-ae2f6f954ded";
export const PROPERTY_PLOT_DIMENSIONS_FIELD_ID = "018e1d4b-7034-4562-9df2-d3ffa89dd6d1";
export const PROPERTY_POWER_BACKUP_FIELD_ID = "71ca4593-32b9-4b68-aaa6-1594537a01ea";
export const PROPERTY_SURVEY_NUMBER_FIELD_ID = "9597cae5-c26d-4682-8c8d-916065cfb1da";
export const PROPERTY_AREA_UNIT_FIELD_ID = "724b3df7-316e-4931-907f-2bd7f5c046da";
export const PROPERTY_SUPER_BUILT_UP_AREA_FIELD_ID = "684dde69-d9a8-40a8-b95e-97238935e4a7";
export const PROPERTY_ELECTRICITY_CONNECTION_FIELD_ID = "ea77f141-ef67-470d-82b9-7c32d919742e";
export const PROPERTY_IS_CORNER_PLOT_FIELD_ID = "d9b95a6b-ae48-44ce-9e2f-92fa61855a65";
export const PROPERTY_RERA_NUMBER_PROPERTY_FIELD_ID = "cef555bd-ce16-4a12-8fba-7666311e630d";
export const PROPERTY_NUMBER_OF_OPEN_SIDES_FIELD_ID = "70902a78-0626-429d-9f61-5523ba215e36";
export const PROPERTY_PROPERTY_TAX_ID_FIELD_ID = "971486b6-4454-4d3f-8651-81c277d76dc9";
export const PROPERTY_FURNISHING_DETAILS_FIELD_ID = "19d4df10-786a-46c5-8bc3-25b5e9732782";
export const PROPERTY_PROPERTY_CATEGORY_FIELD_ID = "429c99cb-49d9-40a6-a706-c6c6bf526c76";
export const PROPERTY_NAME_FIELD_ID = "bdf246a1-5470-5f4b-aa5c-63fdb6bed7d8";
export const PROPERTY_ROAD_WIDTH_FEET_FIELD_ID = "a33ba5a0-969f-4c8f-9b89-482077c8b998";
export const PROPERTY_OWNERSHIP_TYPE_FIELD_ID = "67c59b01-ba05-4f21-911f-4cb2f57760f7";
export const PROPERTY_LIFT_AVAILABLE_FIELD_ID = "b088d122-7140-40ea-b28a-b21fc55f03bd";
export const PROPERTY_CONTAINER_ACCESS_FIELD_ID = "a771e74c-894b-4321-a110-02794c68c480";
export const PROPERTY_CITY_FIELD_ID = "9ee3aa51-5b59-4516-ac6c-953574a83383";
export const PROPERTY_CEILING_HEIGHT_FEET_FIELD_ID = "c6b4fd43-a934-490b-91d5-90555e21f13b";
export const PROPERTY_FURNISHING_STATUS_FIELD_ID = "5bb49c0b-d72f-4459-9fd1-659d8db37e0d";
export const PROPERTY_BATHROOMS_FIELD_ID = "3ddb2c11-bee6-41d9-ba01-1881870f3352";
export const PROPERTY_CARPET_AREA_FIELD_ID = "9620c4c2-3144-49e8-b956-59e70b224946";
export const PROPERTY_LAND_CLASSIFICATION_FIELD_ID = "c697292a-1c88-49bf-89db-aeccf3280be1";
export const PROPERTY_MAINTENANCE_CHARGE_PER_SQ_FT_FIELD_ID = "a0101fab-f952-467a-95bb-9d2190774245";
export const PROPERTY_BOREWELL_COUNT_FIELD_ID = "34bbaab6-3332-430b-8648-8e8f18c08009";
export const PROPERTY_SHED_AREA_SQ_FT_FIELD_ID = "38c013a8-70fb-4cbb-bff1-abe53faf27ed";
export const PROPERTY_POSSESSION_STATUS_FIELD_ID = "ef568cdd-92d8-44f1-ac4f-ff73a2988a34";
export const PROPERTY_UNIT_NUMBER_FIELD_ID = "46fded79-fad9-4601-acca-de5d4f07c3ae";
export const PROPERTY_CURRENT_CROP_FIELD_ID = "fac707c7-3dd3-408c-9c91-172cd0af66e7";
export const PROPERTY_POWER_LOAD_KVA_FIELD_ID = "f7cf0164-7488-46c9-98a9-6acf7885f128";
export const PROPERTY_OPEN_LAND_SQ_FT_FIELD_ID = "8c92043a-fe95-4a73-9f98-db338ff921b3";
export const PROPERTY_FEATURES_FIELD_ID = "1dc1f125-19a8-4cdf-965c-bf9315888beb";
export const PROPERTY_BHK_CONFIGURATION_FIELD_ID = "89e5cb20-002e-4c7d-9d84-edd0444b0f40";
export const PROPERTY_CURRENTLY_LEASED_FIELD_ID = "969fd156-2f2b-4703-85e8-40771327b1bd";
export const PROPERTY_ROAD_ACCESS_FIELD_ID = "38987e79-38d7-4fb7-9d50-5f4b9bacacbe";
export const PROPERTY_BUYER_ELIGIBILITY_RESTRICTED_FIELD_ID = "34304573-f980-4363-9ff7-dd8b18f73cf6";
export const PROPERTY_BOUNDARY_WALL_FIELD_ID = "f049ccfb-c230-41db-97f0-739a7c64dd16";
export const PROPERTY_PIN_CODE_FIELD_ID = "118e6392-2e01-4cb7-8103-f9025539ea29";
export const PROPERTY_FIT_OUT_STATUS_FIELD_ID = "bfdd2f9b-4ce1-4691-8ae1-263ccc0f06df";
export const PROPERTY_FACING_FIELD_ID = "b8c727a9-bdb4-45d1-8c47-adeb029f5ed2";
export const PROPERTY_DOCK_LEVELLERS_FIELD_ID = "9bc4b268-2b14-4465-baeb-91a699a2ce16";
export const PROPERTY_FLOOR_NUMBER_FIELD_ID = "6fe53c04-8072-46a5-9526-84938df82b9c";
export const PROPERTY_ANNUAL_PROPERTY_TAX_FIELD_ID = "122e029b-5e79-47ec-aa9d-3c7fff2b8498";
export const PROPERTY_TOTAL_FLOORS_FIELD_ID = "c49ba7b5-bc1a-4f41-9e07-f684d8b3ae55";
export const PROPERTY_FULL_ADDRESS_FIELD_ID = "6f4680e3-a6be-402f-acb4-4f18a3b52603";
export const PROPERTY_SIGNAGE_RIGHTS_FIELD_ID = "c5b41a12-2574-4f33-b99f-5702e855125e";
export const PROPERTY_PLOT_AREA_FIELD_ID = "a0d3a5d5-18de-4358-8ef5-d4961b04edfd";
export const PROPERTY_LEASE_EXPIRY_DATE_FIELD_ID = "2a2e2a8f-d53e-476f-b83f-e2a8a4b23deb";
export const PROPERTY_FRONTAGE_FEET_FIELD_ID = "1f232c21-8977-49e4-a617-06bf75fbd37d";
export const PROPERTY_LOCALITY_FIELD_ID = "91c0e497-09a2-4726-ad6d-a9f63822e38c";
export const PROPERTY_CONVERSION_STATUS_FIELD_ID = "8250db2d-204f-44c3-8ae2-114544e53bd3";

export default defineObject({
  universalIdentifier: PROPERTY_UNIVERSAL_IDENTIFIER,
  nameSingular: "property",
  namePlural: "properties",
  labelSingular: "Property",
  labelPlural: "Properties",
  description: "A physical property or land parcel. Permanent record, survives across listings.",
  icon: "IconHome",
  labelIdentifierFieldMetadataUniversalIdentifier: PROPERTY_NAME_FIELD_ID,
  fields: [
    {
      universalIdentifier: PROPERTY_PHOTOS_FIELD_ID,
      type: FieldType.FILES,
      name: "photos",
      label: "Photos",
      icon: "IconPhoto",
      isNullable: true,
      universalSettings: {"maxNumberOfValues": 30},
    },
    {
      universalIdentifier: PROPERTY_BEDROOMS_FIELD_ID,
      type: FieldType.NUMBER,
      name: "bedrooms",
      label: "Bedrooms",
      icon: "IconBed",
      isNullable: true,
      universalSettings: { dataType: NumberDataType.INT },
    },
    {
      universalIdentifier: PROPERTY_OPEN_PARKING_FIELD_ID,
      type: FieldType.NUMBER,
      name: "openParking",
      label: "Open Parking",
      icon: "IconParking",
      isNullable: true,
      universalSettings: { dataType: NumberDataType.INT },
    },
    {
      universalIdentifier: PROPERTY_WATER_SOURCE_FIELD_ID,
      type: FieldType.MULTI_SELECT,
      name: "waterSource",
      label: "Water Source",
      description: "Covers both urban and agricultural sources.",
      icon: "IconDroplet",
      isNullable: true,
      options: [
      { value: "CORPORATION", label: "Corporation / Municipal", position: 0, color: "green" },
      { value: "BOREWELL", label: "Borewell", position: 1, color: "turquoise" },
      { value: "TANKER", label: "Tanker", position: 2, color: "sky" },
      { value: "OPEN_WELL", label: "Open Well", position: 3, color: "blue" },
      { value: "CANAL", label: "Canal", position: 4, color: "purple" },
      { value: "RIVER", label: "River", position: 5, color: "pink" },
      { value: "LAKE", label: "Lake", position: 6, color: "red" },
      { value: "RAIN_FED", label: "Rain-fed", position: 7, color: "orange" },
      { value: "NONE", label: "No Source", position: 8, color: "yellow" },
      ],
    },
    {
      universalIdentifier: PROPERTY_AGE_OF_PROPERTY_FIELD_ID,
      type: FieldType.SELECT,
      name: "ageOfProperty",
      label: "Age of Property",
      icon: "IconCalendarTime",
      isNullable: true,
      options: [
      { value: "NEW", label: "New", position: 0, color: "green" },
      { value: "Y0_1", label: "0-1 years", position: 1, color: "turquoise" },
      { value: "Y1_5", label: "1-5 years", position: 2, color: "sky" },
      { value: "Y5_10", label: "5-10 years", position: 3, color: "blue" },
      { value: "Y10_15", label: "10-15 years", position: 4, color: "purple" },
      { value: "Y15_PLUS", label: "15+ years", position: 5, color: "pink" },
      ],
    },
    {
      universalIdentifier: PROPERTY_COVERED_PARKING_FIELD_ID,
      type: FieldType.NUMBER,
      name: "coveredParking",
      label: "Covered Parking",
      icon: "IconCar",
      isNullable: true,
      universalSettings: { dataType: NumberDataType.INT },
    },
    {
      universalIdentifier: PROPERTY_VASTU_COMPLIANT_FIELD_ID,
      type: FieldType.BOOLEAN,
      name: "vastuCompliant",
      label: "Vastu Compliant",
      icon: "IconCompass",
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_BUILT_UP_AREA_FIELD_ID,
      type: FieldType.NUMBER,
      name: "builtUpArea",
      label: "Built-up Area",
      description: "Carpet area plus walls.",
      icon: "IconRuler",
      isNullable: true,
      universalSettings: { dataType: NumberDataType.FLOAT },
    },
    {
      universalIdentifier: PROPERTY_EXISTING_RENT_FIELD_ID,
      type: FieldType.CURRENCY,
      name: "existingRent",
      label: "Existing Rent",
      icon: "IconCash",
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_SOCIETY_NAME_FIELD_ID,
      type: FieldType.TEXT,
      name: "societyName",
      label: "Society Name",
      icon: "IconBuildingCommunity",
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_KHATA_TYPE_FIELD_ID,
      type: FieldType.SELECT,
      name: "khataType",
      label: "Khata Type",
      description: "B Khata properties generally cannot get bank loans. Check before taking clients on site visits.",
      icon: "IconFileCertificate",
      isNullable: true,
      options: [
      { value: "A_KHATA", label: "A Khata", position: 0, color: "green" },
      { value: "B_KHATA", label: "B Khata", position: 1, color: "red" },
      { value: "NOT_APPLICABLE", label: "Not Applicable", position: 2, color: "gray" },
      ],
    },
    {
      universalIdentifier: PROPERTY_PROPERTY_TYPE_FIELD_ID,
      type: FieldType.SELECT,
      name: "propertyType",
      label: "Property Type",
      icon: "IconHome2",
      isNullable: true,
      options: [
      { value: "APARTMENT", label: "Apartment / Flat", position: 0, color: "blue" },
      { value: "INDEPENDENT_HOUSE", label: "Independent House", position: 1, color: "blue" },
      { value: "VILLA", label: "Villa", position: 2, color: "blue" },
      { value: "BUILDER_FLOOR", label: "Builder Floor", position: 3, color: "blue" },
      { value: "ROW_HOUSE", label: "Row House", position: 4, color: "blue" },
      { value: "DUPLEX", label: "Duplex", position: 5, color: "blue" },
      { value: "TRIPLEX", label: "Triplex", position: 6, color: "blue" },
      { value: "PENTHOUSE", label: "Penthouse", position: 7, color: "blue" },
      { value: "STUDIO", label: "Studio / 1RK", position: 8, color: "blue" },
      { value: "SERVICED_APARTMENT", label: "Serviced Apartment", position: 9, color: "blue" },
      { value: "BUNGALOW", label: "Bungalow", position: 10, color: "blue" },
      { value: "FARMHOUSE", label: "Farmhouse", position: 11, color: "green" },
      { value: "CHAWL", label: "Chawl", position: 12, color: "blue" },
      { value: "RESIDENTIAL_PLOT", label: "Residential Plot", position: 13, color: "turquoise" },
      { value: "PG_HOSTEL", label: "PG / Hostel", position: 14, color: "blue" },
      { value: "CO_LIVING", label: "Co-living Unit", position: 15, color: "blue" },
      { value: "OFFICE_SPACE", label: "Office Space", position: 16, color: "purple" },
      { value: "CO_WORKING", label: "Co-working Space", position: 17, color: "purple" },
      { value: "BUSINESS_CENTER", label: "Business Center", position: 18, color: "purple" },
      { value: "RETAIL_SHOP", label: "Retail Shop", position: 19, color: "purple" },
      { value: "SHOWROOM", label: "Showroom", position: 20, color: "purple" },
      { value: "COMMERCIAL_UNIT", label: "Commercial Complex Unit", position: 21, color: "purple" },
      { value: "RESTAURANT_SPACE", label: "Restaurant / Cafe Space", position: 22, color: "purple" },
      { value: "HOTEL_RESORT", label: "Hotel / Resort", position: 23, color: "purple" },
      { value: "BANQUET_HALL", label: "Banquet Hall", position: 24, color: "purple" },
      { value: "CLINIC_HOSPITAL", label: "Clinic / Hospital Space", position: 25, color: "purple" },
      { value: "COMMERCIAL_PLOT", label: "Commercial Plot", position: 26, color: "turquoise" },
      { value: "WAREHOUSE", label: "Warehouse / Godown", position: 27, color: "orange" },
      { value: "FACTORY", label: "Factory", position: 28, color: "orange" },
      { value: "INDUSTRIAL_SHED", label: "Industrial Shed", position: 29, color: "orange" },
      { value: "MANUFACTURING_UNIT", label: "Manufacturing Unit", position: 30, color: "orange" },
      { value: "COLD_STORAGE", label: "Cold Storage", position: 31, color: "orange" },
      { value: "INDUSTRIAL_PLOT", label: "Industrial Plot", position: 32, color: "turquoise" },
      { value: "AGRICULTURAL_LAND", label: "Agricultural Land", position: 33, color: "green" },
      { value: "FARM_LAND", label: "Farm Land", position: 34, color: "green" },
      { value: "ORCHARD", label: "Orchard / Plantation", position: 35, color: "green" },
      { value: "POULTRY_DAIRY", label: "Poultry / Dairy Farm", position: 36, color: "green" },
      { value: "FARMHOUSE_WITH_LAND", label: "Farmhouse with Land", position: 37, color: "green" },
      { value: "SCHOOL_COLLEGE", label: "School / College Building", position: 38, color: "sky" },
      { value: "HOSPITAL_BUILDING", label: "Hospital Building", position: 39, color: "sky" },
      { value: "TRUST_PROPERTY", label: "Religious / Trust Property", position: 40, color: "sky" },
      { value: "INSTITUTIONAL_PLOT", label: "Institutional Plot", position: 41, color: "sky" },
      { value: "PARKING_SPACE", label: "Parking Space", position: 42, color: "gray" },
      { value: "HOARDING_SITE", label: "Hoarding / Advertising Site", position: 43, color: "gray" },
      { value: "JOINT_DEVELOPMENT", label: "Land for Joint Development", position: 44, color: "gray" },
      { value: "REDEVELOPMENT", label: "Redevelopment Opportunity", position: 45, color: "gray" },
      ],
    },
    {
      universalIdentifier: PROPERTY_POLLUTION_BOARD_CATEGORY_FIELD_ID,
      type: FieldType.SELECT,
      name: "pollutionBoardCategory",
      label: "Pollution Board Category",
      description: "Determines what industries can legally operate there.",
      icon: "IconAlertHexagon",
      isNullable: true,
      options: [
      { value: "RED", label: "Red", position: 0, color: "red" },
      { value: "ORANGE", label: "Orange", position: 1, color: "orange" },
      { value: "GREEN", label: "Green", position: 2, color: "green" },
      { value: "WHITE", label: "White", position: 3, color: "gray" },
      ],
    },
    {
      universalIdentifier: PROPERTY_RTC_PAHANI_NUMBER_FIELD_ID,
      type: FieldType.TEXT,
      name: "rtcPahaniNumber",
      label: "RTC / Pahani / 7-12 Number",
      description: "RTC or Pahani in Karnataka, 7/12 Extract in Maharashtra. The core land record.",
      icon: "IconFileDescription",
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_FENCING_FIELD_ID,
      type: FieldType.BOOLEAN,
      name: "fencing",
      label: "Fencing",
      icon: "IconFence",
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_RENTAL_YIELD_PCT_FIELD_ID,
      type: FieldType.NUMBER,
      name: "rentalYieldPct",
      label: "Rental Yield %",
      description: "How commercial investors compare properties.",
      icon: "IconTrendingUp",
      isNullable: true,
      universalSettings: { dataType: NumberDataType.FLOAT },
    },
    {
      universalIdentifier: PROPERTY_LAYOUT_APPROVAL_FIELD_ID,
      type: FieldType.SELECT,
      name: "layoutApproval",
      label: "Layout Approval",
      description: "Unapproved layouts block bank loans.",
      icon: "IconStamp",
      isNullable: true,
      options: [
      { value: "BDA", label: "BDA", position: 0, color: "green" },
      { value: "BMRDA", label: "BMRDA", position: 1, color: "turquoise" },
      { value: "DTCP", label: "DTCP", position: 2, color: "sky" },
      { value: "CMDA", label: "CMDA", position: 3, color: "blue" },
      { value: "HMDA", label: "HMDA", position: 4, color: "purple" },
      { value: "MHADA", label: "MHADA", position: 5, color: "pink" },
      { value: "GRAM_PANCHAYAT", label: "Gram Panchayat", position: 6, color: "yellow" },
      { value: "UNAPPROVED", label: "Unapproved", position: 7, color: "red" },
      ],
    },
    {
      universalIdentifier: PROPERTY_GATED_COMMUNITY_FIELD_ID,
      type: FieldType.BOOLEAN,
      name: "gatedCommunity",
      label: "Gated Community",
      icon: "IconFenceOutline",
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_EAVE_HEIGHT_FEET_FIELD_ID,
      type: FieldType.NUMBER,
      name: "eaveHeightFeet",
      label: "Eave Height (ft)",
      description: "Determines racking capacity.",
      icon: "IconArrowUp",
      isNullable: true,
      universalSettings: { dataType: NumberDataType.FLOAT },
    },
    {
      universalIdentifier: PROPERTY_CIRCLE_RATE_VALUE_FIELD_ID,
      type: FieldType.CURRENCY,
      name: "circleRateValue",
      label: "Circle Rate Value",
      description: "Government guidance value. Stamp duty is charged on whichever is higher, this or the agreement value.",
      icon: "IconReceiptTax",
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_PLOT_DIMENSIONS_FIELD_ID,
      type: FieldType.TEXT,
      name: "plotDimensions",
      label: "Plot Dimensions",
      description: "Length x breadth, in feet.",
      icon: "IconRulerMeasure",
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_POWER_BACKUP_FIELD_ID,
      type: FieldType.SELECT,
      name: "powerBackup",
      label: "Power Backup",
      icon: "IconBattery",
      isNullable: true,
      options: [
      { value: "NONE", label: "None", position: 0, color: "gray" },
      { value: "PARTIAL", label: "Partial", position: 1, color: "yellow" },
      { value: "FULL", label: "Full", position: 2, color: "green" },
      ],
    },
    {
      universalIdentifier: PROPERTY_SURVEY_NUMBER_FIELD_ID,
      type: FieldType.TEXT,
      name: "surveyNumber",
      label: "Survey Number",
      icon: "IconMapPin2",
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_AREA_UNIT_FIELD_ID,
      type: FieldType.SELECT,
      name: "areaUnit",
      label: "Area Unit",
      icon: "IconRuler3",
      isNullable: true,
      options: [
      { value: "SQ_FT", label: "Sq Ft", position: 0, color: "green" },
      { value: "SQ_M", label: "Sq M", position: 1, color: "turquoise" },
      { value: "SQ_YARD", label: "Sq Yard", position: 2, color: "sky" },
      { value: "ACRE", label: "Acre", position: 3, color: "blue" },
      { value: "GUNTHA", label: "Guntha", position: 4, color: "purple" },
      { value: "CENT", label: "Cent", position: 5, color: "pink" },
      { value: "BIGHA", label: "Bigha", position: 6, color: "red" },
      { value: "HECTARE", label: "Hectare", position: 7, color: "orange" },
      ],
    },
    {
      universalIdentifier: PROPERTY_SUPER_BUILT_UP_AREA_FIELD_ID,
      type: FieldType.NUMBER,
      name: "superBuiltUpArea",
      label: "Super Built-up Area",
      description: "What portals advertise. Includes common area share.",
      icon: "IconRulerMeasure",
      isNullable: true,
      universalSettings: { dataType: NumberDataType.FLOAT },
    },
    {
      universalIdentifier: PROPERTY_ELECTRICITY_CONNECTION_FIELD_ID,
      type: FieldType.BOOLEAN,
      name: "electricityConnection",
      label: "Electricity Connection",
      icon: "IconBolt",
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_IS_CORNER_PLOT_FIELD_ID,
      type: FieldType.BOOLEAN,
      name: "isCornerPlot",
      label: "Corner Plot",
      icon: "IconCornerUpRight",
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_RERA_NUMBER_PROPERTY_FIELD_ID,
      type: FieldType.TEXT,
      name: "reraNumberProperty",
      label: "RERA Number",
      icon: "IconShieldCheck",
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_NUMBER_OF_OPEN_SIDES_FIELD_ID,
      type: FieldType.SELECT,
      name: "numberOfOpenSides",
      label: "Open Sides",
      icon: "IconBorderSides",
      isNullable: true,
      options: [
      { value: "ONE", label: "1", position: 0, color: "green" },
      { value: "TWO", label: "2", position: 1, color: "turquoise" },
      { value: "THREE", label: "3", position: 2, color: "sky" },
      { value: "FOUR", label: "4", position: 3, color: "blue" },
      ],
    },
    {
      universalIdentifier: PROPERTY_PROPERTY_TAX_ID_FIELD_ID,
      type: FieldType.TEXT,
      name: "propertyTaxId",
      label: "Property Tax ID",
      description: "Khata / Patta / Property ID.",
      icon: "IconFileText",
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_FURNISHING_DETAILS_FIELD_ID,
      type: FieldType.MULTI_SELECT,
      name: "furnishingDetails",
      label: "Furnishing Details",
      icon: "IconArmchair",
      isNullable: true,
      options: [
      { value: "MODULAR_KITCHEN", label: "Modular Kitchen", position: 0, color: "green" },
      { value: "WARDROBES", label: "Wardrobes", position: 1, color: "turquoise" },
      { value: "ACS", label: "ACs", position: 2, color: "sky" },
      { value: "BEDS", label: "Beds", position: 3, color: "blue" },
      { value: "SOFA", label: "Sofa", position: 4, color: "purple" },
      { value: "FRIDGE", label: "Fridge", position: 5, color: "pink" },
      { value: "WASHING_MACHINE", label: "Washing Machine", position: 6, color: "red" },
      { value: "GEYSER", label: "Geyser", position: 7, color: "orange" },
      { value: "CURTAINS", label: "Curtains", position: 8, color: "yellow" },
      { value: "LIGHT_FITTINGS", label: "Light Fittings", position: 9, color: "gray" },
      ],
    },
    {
      universalIdentifier: PROPERTY_PROPERTY_CATEGORY_FIELD_ID,
      type: FieldType.SELECT,
      name: "propertyCategory",
      label: "Category",
      icon: "IconCategory",
      isNullable: true,
      options: [
      { value: "RESIDENTIAL", label: "Residential", position: 0, color: "blue" },
      { value: "COMMERCIAL", label: "Commercial", position: 1, color: "purple" },
      { value: "INDUSTRIAL", label: "Industrial", position: 2, color: "orange" },
      { value: "AGRICULTURAL", label: "Agricultural", position: 3, color: "green" },
      { value: "INSTITUTIONAL", label: "Institutional", position: 4, color: "sky" },
      { value: "OTHER", label: "Other", position: 5, color: "gray" },
      ],
    },
    {
      universalIdentifier: PROPERTY_NAME_FIELD_ID,
      type: FieldType.TEXT,
      name: "name",
      label: "Name",
      description: "Name",
      icon: "IconAbc",
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_ROAD_WIDTH_FEET_FIELD_ID,
      type: FieldType.NUMBER,
      name: "roadWidthFeet",
      label: "Road Width (ft)",
      description: "Width of the road the plot faces. Directly affects value and buildability.",
      icon: "IconRoad",
      isNullable: true,
      universalSettings: { dataType: NumberDataType.FLOAT },
    },
    {
      universalIdentifier: PROPERTY_OWNERSHIP_TYPE_FIELD_ID,
      type: FieldType.SELECT,
      name: "ownershipType",
      label: "Ownership Type",
      description: "Power of Attorney properties carry real title risk. Require a legal opinion.",
      icon: "IconCertificate",
      isNullable: true,
      options: [
      { value: "FREEHOLD", label: "Freehold", position: 0, color: "green" },
      { value: "LEASEHOLD", label: "Leasehold", position: 1, color: "yellow" },
      { value: "CO_OP_SOCIETY", label: "Co-operative Society", position: 2, color: "sky" },
      { value: "POWER_OF_ATTORNEY", label: "Power of Attorney", position: 3, color: "red" },
      { value: "JOINT_OWNERSHIP", label: "Joint Ownership", position: 4, color: "orange" },
      ],
    },
    {
      universalIdentifier: PROPERTY_LIFT_AVAILABLE_FIELD_ID,
      type: FieldType.BOOLEAN,
      name: "liftAvailable",
      label: "Lift Available",
      icon: "IconElevator",
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_CONTAINER_ACCESS_FIELD_ID,
      type: FieldType.BOOLEAN,
      name: "containerAccess",
      label: "Container Truck Access",
      description: "Whether a 40-foot trailer can reach the loading bay.",
      icon: "IconTruck",
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_CITY_FIELD_ID,
      type: FieldType.TEXT,
      name: "city",
      label: "City",
      icon: "IconBuilding",
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_CEILING_HEIGHT_FEET_FIELD_ID,
      type: FieldType.NUMBER,
      name: "ceilingHeightFeet",
      label: "Ceiling Height (ft)",
      icon: "IconArrowsVertical",
      isNullable: true,
      universalSettings: { dataType: NumberDataType.FLOAT },
    },
    {
      universalIdentifier: PROPERTY_FURNISHING_STATUS_FIELD_ID,
      type: FieldType.SELECT,
      name: "furnishingStatus",
      label: "Furnishing",
      icon: "IconSofa",
      isNullable: true,
      options: [
      { value: "UNFURNISHED", label: "Unfurnished", position: 0, color: "gray" },
      { value: "SEMI_FURNISHED", label: "Semi-Furnished", position: 1, color: "yellow" },
      { value: "FULLY_FURNISHED", label: "Fully Furnished", position: 2, color: "green" },
      ],
    },
    {
      universalIdentifier: PROPERTY_BATHROOMS_FIELD_ID,
      type: FieldType.NUMBER,
      name: "bathrooms",
      label: "Bathrooms",
      icon: "IconBath",
      isNullable: true,
      universalSettings: { dataType: NumberDataType.INT },
    },
    {
      universalIdentifier: PROPERTY_CARPET_AREA_FIELD_ID,
      type: FieldType.NUMBER,
      name: "carpetArea",
      label: "Carpet Area",
      description: "RERA-mandated disclosure. The only honest area number.",
      icon: "IconRuler2",
      isNullable: true,
      universalSettings: { dataType: NumberDataType.FLOAT },
    },
    {
      universalIdentifier: PROPERTY_LAND_CLASSIFICATION_FIELD_ID,
      type: FieldType.SELECT,
      name: "landClassification",
      label: "Land Classification",
      icon: "IconPlant2",
      isNullable: true,
      options: [
      { value: "DRY", label: "Dry", position: 0, color: "green" },
      { value: "WET", label: "Wet", position: 1, color: "turquoise" },
      { value: "IRRIGATED", label: "Irrigated", position: 2, color: "sky" },
      { value: "GARDEN", label: "Garden", position: 3, color: "blue" },
      { value: "PLANTATION", label: "Plantation", position: 4, color: "purple" },
      ],
    },
    {
      universalIdentifier: PROPERTY_MAINTENANCE_CHARGE_PER_SQ_FT_FIELD_ID,
      type: FieldType.CURRENCY,
      name: "maintenanceChargePerSqFt",
      label: "Maintenance / Sq Ft",
      icon: "IconTool",
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_BOREWELL_COUNT_FIELD_ID,
      type: FieldType.NUMBER,
      name: "borewellCount",
      label: "Borewell Count",
      icon: "IconWell",
      isNullable: true,
      universalSettings: { dataType: NumberDataType.INT },
    },
    {
      universalIdentifier: PROPERTY_SHED_AREA_SQ_FT_FIELD_ID,
      type: FieldType.NUMBER,
      name: "shedAreaSqFt",
      label: "Shed Area (sq ft)",
      icon: "IconBuildingFactory",
      isNullable: true,
      universalSettings: { dataType: NumberDataType.FLOAT },
    },
    {
      universalIdentifier: PROPERTY_POSSESSION_STATUS_FIELD_ID,
      type: FieldType.SELECT,
      name: "possessionStatus",
      label: "Possession Status",
      icon: "IconKey",
      isNullable: true,
      options: [
      { value: "READY_TO_MOVE", label: "Ready to Move", position: 0, color: "green" },
      { value: "UNDER_CONSTRUCTION", label: "Under Construction", position: 1, color: "orange" },
      { value: "NEW_LAUNCH", label: "New Launch", position: 2, color: "blue" },
      ],
    },
    {
      universalIdentifier: PROPERTY_UNIT_NUMBER_FIELD_ID,
      type: FieldType.TEXT,
      name: "unitNumber",
      label: "Unit / Plot Number",
      icon: "IconHash",
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_CURRENT_CROP_FIELD_ID,
      type: FieldType.TEXT,
      name: "currentCrop",
      label: "Current Crop / Plantation",
      icon: "IconWheat",
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_POWER_LOAD_KVA_FIELD_ID,
      type: FieldType.NUMBER,
      name: "powerLoadKva",
      label: "Power Load (KVA)",
      icon: "IconBolt",
      isNullable: true,
      universalSettings: { dataType: NumberDataType.FLOAT },
    },
    {
      universalIdentifier: PROPERTY_OPEN_LAND_SQ_FT_FIELD_ID,
      type: FieldType.NUMBER,
      name: "openLandSqFt",
      label: "Open Land (sq ft)",
      icon: "IconSquare",
      isNullable: true,
      universalSettings: { dataType: NumberDataType.FLOAT },
    },
    {
      universalIdentifier: PROPERTY_FEATURES_FIELD_ID,
      type: FieldType.MULTI_SELECT,
      name: "features",
      label: "Features",
      icon: "IconSparkles",
      isNullable: true,
      options: [
      { value: "POOL", label: "Swimming Pool", position: 0, color: "green" },
      { value: "GYM", label: "Gym", position: 1, color: "turquoise" },
      { value: "CLUBHOUSE", label: "Clubhouse", position: 2, color: "sky" },
      { value: "PARK", label: "Park / Garden", position: 3, color: "blue" },
      { value: "SECURITY", label: "24x7 Security", position: 4, color: "purple" },
      { value: "CCTV", label: "CCTV", position: 5, color: "pink" },
      { value: "PLAY_AREA", label: "Kids Play Area", position: 6, color: "red" },
      { value: "SPORTS", label: "Sports Court", position: 7, color: "orange" },
      { value: "CORNER_UNIT", label: "Corner Unit", position: 8, color: "yellow" },
      { value: "PARK_FACING", label: "Park Facing", position: 9, color: "gray" },
      { value: "MAIN_ROAD", label: "Main Road Facing", position: 10, color: "green" },
      { value: "SOLAR", label: "Solar", position: 11, color: "turquoise" },
      { value: "RAINWATER", label: "Rainwater Harvesting", position: 12, color: "sky" },
      { value: "PET_FRIENDLY", label: "Pet Friendly", position: 13, color: "blue" },
      ],
    },
    {
      universalIdentifier: PROPERTY_BHK_CONFIGURATION_FIELD_ID,
      type: FieldType.SELECT,
      name: "bhkConfiguration",
      label: "BHK",
      description: "Residential built units only. Left blank for plots, shops, warehouses and land.",
      icon: "IconBed",
      isNullable: true,
      options: [
      { value: "RK1", label: "1 RK", position: 0, color: "green" },
      { value: "BHK1", label: "1 BHK", position: 1, color: "turquoise" },
      { value: "BHK1_5", label: "1.5 BHK", position: 2, color: "sky" },
      { value: "BHK2", label: "2 BHK", position: 3, color: "blue" },
      { value: "BHK2_5", label: "2.5 BHK", position: 4, color: "purple" },
      { value: "BHK3", label: "3 BHK", position: 5, color: "pink" },
      { value: "BHK3_5", label: "3.5 BHK", position: 6, color: "red" },
      { value: "BHK4", label: "4 BHK", position: 7, color: "orange" },
      { value: "BHK5", label: "5 BHK", position: 8, color: "yellow" },
      { value: "BHK6", label: "6 BHK", position: 9, color: "gray" },
      { value: "BHK6_PLUS", label: "6+ BHK", position: 10, color: "green" },
      ],
    },
    {
      universalIdentifier: PROPERTY_CURRENTLY_LEASED_FIELD_ID,
      type: FieldType.BOOLEAN,
      name: "currentlyLeased",
      label: "Currently Leased",
      description: "If tenanted, the sale is an investment sale.",
      icon: "IconFileText",
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_ROAD_ACCESS_FIELD_ID,
      type: FieldType.SELECT,
      name: "roadAccess",
      label: "Road Access",
      icon: "IconRoadSign",
      isNullable: true,
      options: [
      { value: "TAR_ROAD", label: "Tar Road", position: 0, color: "green" },
      { value: "MUD_ROAD", label: "Mud Road", position: 1, color: "yellow" },
      { value: "NO_DIRECT_ACCESS", label: "No Direct Access", position: 2, color: "red" },
      ],
    },
    {
      universalIdentifier: PROPERTY_BUYER_ELIGIBILITY_RESTRICTED_FIELD_ID,
      type: FieldType.BOOLEAN,
      name: "buyerEligibilityRestricted",
      label: "Buyer Eligibility Restricted",
      description: "CRITICAL. Karnataka, Maharashtra, Gujarat and others restrict who may buy agricultural land. Some require the buyer to already be an agriculturist. Getting this wrong voids the sale.",
      icon: "IconAlertTriangle",
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_BOUNDARY_WALL_FIELD_ID,
      type: FieldType.SELECT,
      name: "boundaryWall",
      label: "Boundary Wall",
      icon: "IconWall",
      isNullable: true,
      options: [
      { value: "NONE", label: "None", position: 0, color: "gray" },
      { value: "PARTIAL", label: "Partial", position: 1, color: "yellow" },
      { value: "COMPLETE", label: "Complete", position: 2, color: "green" },
      ],
    },
    {
      universalIdentifier: PROPERTY_PIN_CODE_FIELD_ID,
      type: FieldType.TEXT,
      name: "pinCode",
      label: "PIN Code",
      icon: "IconMailbox",
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_FIT_OUT_STATUS_FIELD_ID,
      type: FieldType.SELECT,
      name: "fitOutStatus",
      label: "Fit-out Status",
      icon: "IconBuildingWarehouse",
      isNullable: true,
      options: [
      { value: "BARE_SHELL", label: "Bare Shell", position: 0, color: "gray" },
      { value: "WARM_SHELL", label: "Warm Shell", position: 1, color: "yellow" },
      { value: "FULLY_FITTED", label: "Fully Fitted", position: 2, color: "green" },
      { value: "PLUG_AND_PLAY", label: "Plug and Play", position: 3, color: "turquoise" },
      ],
    },
    {
      universalIdentifier: PROPERTY_FACING_FIELD_ID,
      type: FieldType.SELECT,
      name: "facing",
      label: "Facing",
      description: "Vastu preference. A genuine deal-breaker for many Indian buyers.",
      icon: "IconCompass",
      isNullable: true,
      options: [
      { value: "NORTH", label: "North", position: 0, color: "green" },
      { value: "NORTH_EAST", label: "North-East", position: 1, color: "turquoise" },
      { value: "EAST", label: "East", position: 2, color: "sky" },
      { value: "SOUTH_EAST", label: "South-East", position: 3, color: "blue" },
      { value: "SOUTH", label: "South", position: 4, color: "purple" },
      { value: "SOUTH_WEST", label: "South-West", position: 5, color: "pink" },
      { value: "WEST", label: "West", position: 6, color: "red" },
      { value: "NORTH_WEST", label: "North-West", position: 7, color: "orange" },
      ],
    },
    {
      universalIdentifier: PROPERTY_DOCK_LEVELLERS_FIELD_ID,
      type: FieldType.NUMBER,
      name: "dockLevellers",
      label: "Dock Levellers",
      icon: "IconTruckLoading",
      isNullable: true,
      universalSettings: { dataType: NumberDataType.INT },
    },
    {
      universalIdentifier: PROPERTY_FLOOR_NUMBER_FIELD_ID,
      type: FieldType.NUMBER,
      name: "floorNumber",
      label: "Floor Number",
      icon: "IconStairs",
      isNullable: true,
      universalSettings: { dataType: NumberDataType.INT },
    },
    {
      universalIdentifier: PROPERTY_ANNUAL_PROPERTY_TAX_FIELD_ID,
      type: FieldType.CURRENCY,
      name: "annualPropertyTax",
      label: "Annual Property Tax",
      icon: "IconReceipt",
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_TOTAL_FLOORS_FIELD_ID,
      type: FieldType.NUMBER,
      name: "totalFloors",
      label: "Total Floors",
      icon: "IconBuilding",
      isNullable: true,
      universalSettings: { dataType: NumberDataType.INT },
    },
    {
      universalIdentifier: PROPERTY_FULL_ADDRESS_FIELD_ID,
      type: FieldType.ADDRESS,
      name: "fullAddress",
      label: "Address",
      icon: "IconMapPin",
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_SIGNAGE_RIGHTS_FIELD_ID,
      type: FieldType.BOOLEAN,
      name: "signageRights",
      label: "Signage Rights",
      icon: "IconBadgeAd",
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_PLOT_AREA_FIELD_ID,
      type: FieldType.NUMBER,
      name: "plotArea",
      label: "Plot Area",
      icon: "IconVector",
      isNullable: true,
      universalSettings: { dataType: NumberDataType.FLOAT },
    },
    {
      universalIdentifier: PROPERTY_LEASE_EXPIRY_DATE_FIELD_ID,
      type: FieldType.DATE,
      name: "leaseExpiryDate",
      label: "Lease Expiry",
      icon: "IconCalendarX",
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_FRONTAGE_FEET_FIELD_ID,
      type: FieldType.NUMBER,
      name: "frontageFeet",
      label: "Frontage (ft)",
      description: "Retail value is largely frontage.",
      icon: "IconRulerMeasure",
      isNullable: true,
      universalSettings: { dataType: NumberDataType.FLOAT },
    },
    {
      universalIdentifier: PROPERTY_LOCALITY_FIELD_ID,
      type: FieldType.TEXT,
      name: "locality",
      label: "Locality",
      description: "Primary search dimension in India.",
      icon: "IconMap2",
      isNullable: true,
    },
    {
      universalIdentifier: PROPERTY_CONVERSION_STATUS_FIELD_ID,
      type: FieldType.SELECT,
      name: "conversionStatus",
      label: "Conversion Status",
      icon: "IconTransform",
      isNullable: true,
      options: [
      { value: "AGRICULTURAL", label: "Agricultural", position: 0, color: "yellow" },
      { value: "DC_CONVERTED", label: "DC Converted", position: 1, color: "green" },
      { value: "NA_CONVERTED", label: "NA Converted", position: 2, color: "green" },
      { value: "NOT_REQUIRED", label: "Not Required", position: 3, color: "gray" },
      ],
    },
  ],
});
